/**
 * Generated from src/http/openapi.json by scripts/generate-api-contracts.mjs.
 * Do not edit this file directly; run `npm run generate:api-contracts`.
 */
// schema-sha256: 8e925ac193e51128e8d32aabf0a21d8ce6b1dafb2da8a1d0880a900ba89c7ebb

/**
 * @typedef {object} HealthStatusDto
 * @property {"ok"} status
 */

/**
 * @typedef {object} AuthStatusDto
 * @property {boolean} authenticated
 * @property {boolean} token_configured
 * @property {boolean} bootstrap_allowed
 */

/**
 * @typedef {object} AuthLoginRequestDto
 * @property {string} token
 */

/**
 * @typedef {object} RedactedQbServerDto
 * @property {string} id
 * @property {string} name
 * @property {string} base_url
 * @property {string} username
 * @property {boolean} insecure_tls
 * @property {boolean} has_password
 */

/**
 * @typedef {object} SubscriptionCategoryDto
 * @property {string} name
 * @property {string} wanted_tag
 * @property {string} qb_server_id
 * @property {string} qb_category
 * @property {string} qb_save_dir_name
 * @property {string} download_dir
 * @property {string} link_target_dir
 */

/**
 * @typedef {object} SubscriptionWatcherDto
 * @property {boolean} enabled
 * @property {boolean} dry_run
 * @property {number} poll_interval_secs
 * @property {number} library_limit
 * @property {number} max_retries
 * @property {number} search_interval_secs
 * @property {number} progress_interval_secs
 * @property {number} link_retry_interval_secs
 * @property {number} system_retry_interval_secs
 * @property {boolean} bootstrap_existing_as_skipped
 */

/** @typedef {"all" | "any"} TorrentRuleMatchMode */

/**
 * @typedef {object} TorrentMatchRuleDto
 * @property {string} name
 * @property {number} priority
 * @property {TorrentRuleMatchMode} mode
 * @property {string[]} title_keywords
 * @property {string[]} resolution_keywords
 * @property {string[]} source_keywords
 */

/**
 * @typedef {object} ConfigResponseDto
 * @property {number} revision
 * @property {string} listen_ip
 * @property {number} listen_port
 * @property {boolean} has_tmdb_api_key
 * @property {boolean} has_mteam_api_key
 * @property {boolean} has_douban_cookie
 * @property {boolean} has_admin_token
 * @property {RedactedQbServerDto[]} qb_servers
 * @property {SubscriptionCategoryDto[]} subscription_categories
 * @property {SubscriptionWatcherDto} subscription_watcher
 * @property {TorrentMatchRuleDto[]} torrent_match_rules
 * @property {string[]} allowed_origins
 * @property {boolean} secure_cookie
 * @property {boolean} restart_required
 */

/**
 * @typedef {object} QbServerPatchDto
 * @property {string=} id
 * @property {string=} name
 * @property {string} base_url
 * @property {string=} username
 * @property {boolean=} insecure_tls
 * @property {string=} password
 * @property {boolean=} clear_password
 */

/**
 * @typedef {object} ConfigUpdateDto
 * @property {number} expected_revision
 * @property {boolean=} confirm_enable_automation
 * @property {string=} listen_ip
 * @property {number=} listen_port
 * @property {string=} tmdb_api_key
 * @property {boolean=} clear_tmdb_api_key
 * @property {string=} mteam_api_key
 * @property {boolean=} clear_mteam_api_key
 * @property {string=} douban_cookie
 * @property {boolean=} clear_douban_cookie
 * @property {string=} admin_token
 * @property {boolean=} clear_admin_token
 * @property {QbServerPatchDto[]=} qb_servers
 * @property {SubscriptionCategoryDto[]=} subscription_categories
 * @property {SubscriptionWatcherDto=} subscription_watcher
 * @property {TorrentMatchRuleDto[]=} torrent_match_rules
 * @property {string[]=} allowed_origins
 * @property {boolean=} secure_cookie
 */

/**
 * @typedef {object} QbTestRequestDto
 * @property {string} server_id
 */

/**
 * @typedef {object} QbTestResponseDto
 * @property {boolean} ok
 * @property {string} version
 */

/**
 * @typedef {object} QbPushMteamRequestDto
 * @property {string} server_id
 * @property {string} torrent_id
 * @property {string=} category
 * @property {string=} savepath
 */

/**
 * @typedef {object} QbPushMteamResponseDto
 * @property {boolean} ok
 */

/**
 * @typedef {object} SubscriptionPollOutcomeDto
 * @property {string} snapshot_id
 * @property {boolean} snapshot_complete
 * @property {number} fetched_items
 * @property {number} inserted
 * @property {number} updated
 * @property {number} unchanged
 * @property {number} reactivated
 * @property {number} deactivated
 * @property {number} failure_count
 * @property {number} next_poll_at
 * @property {number} polled_at
 */

/** @typedef {"movie" | "tv"} SubscriptionMediaKind */

/** @typedef {"queued" | "meta" | "searching" | "downloading" | "linking" | "completed"} SubscriptionLifecycleState */

/** @typedef {"idle" | "running"} SubscriptionExecutionState */

/** @typedef {"waiting_release" | "failed" | "retry_blocked" | "skipped" | "needs_reconciliation"} SubscriptionAttentionTag */

/** @typedef {"imdb" | "douban" | "keyword"} MteamSearchSource */

/**
 * @typedef {object} MteamTorrentDto
 * @property {string} id
 * @property {string} name
 * @property {string=} small_description
 * @property {number=} size
 * @property {number=} seeders
 * @property {number=} leechers
 * @property {string=} created_at
 */

/**
 * @typedef {object} MteamSearchResponseDto
 * @property {MteamTorrentDto[]} items
 * @property {number} page
 * @property {number} page_size
 */

/** @typedef {"movie" | "tv"} TmdbMediaKind */

/**
 * @typedef {object} TmdbSearchItemDto
 * @property {TmdbMediaKind} media_type
 * @property {number} id
 * @property {string} title
 * @property {string} original_title
 * @property {string} overview
 * @property {string | null} poster_path
 * @property {string | null} poster_url
 * @property {string | null} release_date
 * @property {string | null} first_air_date
 * @property {number | null} vote_average
 */

/**
 * @typedef {object} NamedMediaValueDto
 * @property {number | null} id
 * @property {string} name
 * @property {string | null} english_name
 * @property {string | null} code
 */

/**
 * @typedef {object} TmdbSeasonSummaryDto
 * @property {number} season_number
 * @property {string} name
 * @property {number | null} episode_count
 * @property {string | null} air_date
 * @property {string | null} poster_path
 * @property {string | null} poster_url
 */

/**
 * @typedef {object} TmdbMediaDetailDto
 * @property {TmdbMediaKind} media_type
 * @property {number} id
 * @property {string} title
 * @property {string} original_title
 * @property {string} overview
 * @property {string | null} tagline
 * @property {string | null} poster_path
 * @property {string | null} poster_url
 * @property {string | null} backdrop_path
 * @property {string | null} backdrop_url
 * @property {string | null} release_date
 * @property {string | null} first_air_date
 * @property {string | null} last_air_date
 * @property {number | null} runtime
 * @property {string | null} status
 * @property {number | null} vote_average
 * @property {number | null} vote_count
 * @property {NamedMediaValueDto[]} genres
 * @property {NamedMediaValueDto[]} production_countries
 * @property {NamedMediaValueDto[]} spoken_languages
 * @property {string[]} origin_country
 * @property {string | null} imdb_id
 * @property {string | null} douban_id
 * @property {string | null} douban_url
 * @property {number | null} number_of_seasons
 * @property {number | null} number_of_episodes
 * @property {number[]} episode_run_time
 * @property {NamedMediaValueDto[]} networks
 * @property {string | null} series_type
 * @property {TmdbSeasonSummaryDto[]} seasons
 */

/**
 * @typedef {object} TmdbEpisodeDto
 * @property {number | null} id
 * @property {number} episode_number
 * @property {string} name
 * @property {string} overview
 * @property {string | null} air_date
 * @property {string | null} still_path
 * @property {string | null} still_url
 * @property {number | null} runtime
 * @property {number | null} vote_average
 */

/**
 * @typedef {object} TmdbSeasonDetailDto
 * @property {number | null} id
 * @property {number} season_number
 * @property {string} name
 * @property {string} overview
 * @property {string | null} air_date
 * @property {string | null} poster_path
 * @property {string | null} poster_url
 * @property {TmdbEpisodeDto[]} episodes
 */

/**
 * @typedef {object} SubscriptionSummaryDto
 * @property {string} subject_id
 * @property {number} revision
 * @property {boolean} active
 * @property {number | null} inactive_at
 * @property {string | null} last_seen_snapshot_id
 * @property {SubscriptionMediaKind} media_kind
 * @property {boolean} schedulable
 * @property {string | null} blocked_reason
 * @property {SubscriptionLifecycleState} lifecycle_state
 * @property {SubscriptionExecutionState} execution_state
 * @property {number | null} next_attempt_at
 * @property {number} retry_count
 * @property {number} max_retries
 * @property {boolean} retry_blocked
 * @property {boolean} force_eligible_once
 * @property {number} updated_at
 * @property {string} title
 * @property {number | null} release_year
 * @property {string} poster_url
 * @property {string | null} category_text
 * @property {number | null} douban_sort_time
 * @property {SubscriptionAttentionTag[]} attention_tags
 */

/**
 * @typedef {object} SubscriptionSummaryPageDto
 * @property {SubscriptionSummaryDto[]} items
 * @property {string | null} next_cursor
 */

/**
 * @typedef {object} SubscriptionSourceDto
 * @property {string} cover_url
 * @property {string | null} original_title
 * @property {string[]} aka
 * @property {string[]} languages
 * @property {string[]} countries
 * @property {string[]} genres
 * @property {string[]} directors
 * @property {string[]} actors
 * @property {string | null} date_published
 * @property {string | null} duration
 * @property {string | null} synopsis
 * @property {number | null} rating_value
 * @property {number | null} rating_count
 * @property {string[]} tags
 * @property {string | null} douban_date
 * @property {number | null} douban_return_order
 */

/**
 * @typedef {object} SubscriptionObservationDto
 * @property {number} created_at
 * @property {number} first_seen_at
 * @property {number} last_seen_at
 */

/**
 * @typedef {object} SubscriptionIssueDto
 * @property {"subscription" | "download_artifact" | "link_artifact" | "tv_lane" | "tv_episode"} owner
 * @property {string | null} artifact_id
 * @property {"search" | "progress" | "link" | null} lane
 * @property {number | null} season_number
 * @property {number | null} episode_number
 * @property {string | null} operation
 * @property {string | null} error_type
 * @property {string} message
 * @property {number | null} occurred_at
 */

/**
 * @typedef {object} SubscriptionCandidateDto
 * @property {string} torrent_id
 * @property {string} title
 * @property {string} subtitle
 * @property {string} source
 * @property {string | null} size
 * @property {number | null} seeders
 * @property {number | null} leechers
 * @property {string | null} uploaded_at
 * @property {boolean} selected
 * @property {string | null} matched_rule_name
 * @property {number | null} matched_priority
 * @property {string[]} matched_keywords
 * @property {string | null} excluded_reason
 */

/**
 * @typedef {object} SubscriptionTvEpisodeDto
 * @property {number} season_number
 * @property {number} episode_number
 * @property {string} label
 * @property {"target" | "skipped"} intent
 */

/**
 * @typedef {object} SubscriptionTvDetailDto
 * @property {number} season_number
 * @property {number} episode_total
 * @property {number} target_start_episode
 * @property {number} target_end_episode
 * @property {SubscriptionTvEpisodeDto[]} episodes
 */

/**
 * @typedef {object} SubscriptionDownloadFileDto
 * @property {string} name
 * @property {number} size
 * @property {number} progress
 * @property {number | null} season_number
 * @property {number | null} episode_number
 * @property {number | null} episode_end_number
 * @property {string | null} episode_label
 */

/**
 * @typedef {object} SubscriptionDownloadArtifactDto
 * @property {string} id
 * @property {string} torrent_id
 * @property {string} torrent_title
 * @property {string} qb_server_id
 * @property {string | null} qb_server_name
 * @property {string} qb_category
 * @property {string} qb_save_dir_name
 * @property {string | null} qb_hash
 * @property {string | null} qb_name
 * @property {string | null} qb_state
 * @property {"pushed" | "downloading" | "downloaded" | "missing" | "failed" | "ignored" | "superseded"} state
 * @property {number | null} progress
 * @property {number | null} total_size
 * @property {SubscriptionDownloadFileDto[]} files
 * @property {number | null} pushed_at
 * @property {number | null} checked_at
 * @property {number | null} completed_at
 */

/**
 * @typedef {object} SubscriptionLinkFileDto
 * @property {string} source_path
 * @property {string} target_path
 * @property {number} size
 * @property {"pending" | "linked" | "failed" | "missing" | "conflict"} outcome
 * @property {number | null} season_number
 * @property {number | null} episode_number
 * @property {number | null} episode_end_number
 * @property {string | null} episode_label
 * @property {string | null} error
 */

/**
 * @typedef {object} SubscriptionLinkArtifactDto
 * @property {string} id
 * @property {string} download_artifact_id
 * @property {"planned" | "partial" | "completed" | "failed"} state
 * @property {string | null} source_path
 * @property {string | null} target_dir
 * @property {number} checked_at
 * @property {number | null} completed_at
 * @property {SubscriptionLinkFileDto[]} files
 */

/**
 * @typedef {object} SubscriptionDetailDto
 * @property {SubscriptionSummaryDto} summary
 * @property {SubscriptionSourceDto} source
 * @property {SubscriptionObservationDto} observation
 * @property {SubscriptionIssueDto[]} issues
 * @property {string | null} skip_reason
 * @property {SubscriptionCandidateDto[]} candidates
 * @property {unknown} tv
 * @property {SubscriptionDownloadArtifactDto[]} downloads
 * @property {SubscriptionLinkArtifactDto[]} links
 */

/**
 * @typedef {object} OperationLogEntryDto
 * @property {number} id
 * @property {number} created_at
 * @property {string} category
 * @property {string} action
 * @property {string} target_type
 * @property {string | null} target_id
 * @property {string | null} target_title
 * @property {string} status
 * @property {string} summary
 * @property {string | null} error
 * @property {OperationLogRelatedDto} related
 */

/**
 * @typedef {object} OperationLogRelatedFieldDto
 * @property {string} key
 * @property {string} value
 */

/**
 * @typedef {object} OperationLogRuleEvaluationDto
 * @property {string} rule_name
 * @property {boolean} matched
 * @property {string[]} matched_keywords
 * @property {string[]} missing_keywords
 * @property {string | null} excluded_reason
 */

/**
 * @typedef {object} OperationLogTorrentMatchDto
 * @property {string} torrent_id
 * @property {number | null} seeders
 * @property {number | null} leechers
 * @property {string | null} size
 * @property {string | null} uploaded_at
 * @property {string[]} matched_keywords
 * @property {OperationLogRuleEvaluationDto[]} rule_evaluations
 */

/**
 * @typedef {object} OperationLogRelatedDto
 * @property {OperationLogRelatedFieldDto[]} fields
 * @property {OperationLogTorrentMatchDto[]} torrent_matches
 */

/**
 * @typedef {object} OperationLogPageDto
 * @property {OperationLogEntryDto[]} items
 * @property {number} page
 * @property {number} page_size
 * @property {number} total
 * @property {boolean} has_more
 */

/**
 * @typedef {object} TmdbSearchResponseDto
 * @property {TmdbSearchItemDto[]} movies
 * @property {TmdbSearchItemDto[]} tv
 */

/**
 * @typedef {object} DoubanRatingDto
 * @property {number | null} value
 * @property {number | null} count
 * @property {string} info
 * @property {number | null} star_count
 */

/**
 * @typedef {object} DoubanSearchItemDto
 * @property {string} source
 * @property {string} media_type
 * @property {string} id
 * @property {string} subject_id
 * @property {string} title
 * @property {string} url
 * @property {string} abstract_text
 * @property {string} abstract_2
 * @property {string} cover_url
 * @property {string} poster_url
 * @property {DoubanRatingDto} rating
 * @property {number | null} vote_average
 */

/**
 * @typedef {object} DoubanSearchResponseDto
 * @property {DoubanSearchItemDto[]} items
 * @property {number} page
 * @property {number} page_size
 * @property {boolean} has_more
 */

/**
 * @typedef {object} DoubanSubjectDetailDto
 * @property {string} source
 * @property {string} media_type
 * @property {string} id
 * @property {string} subject_id
 * @property {string} url
 * @property {string} title
 * @property {string=} original_title
 * @property {string[]=} aka
 * @property {string[]=} languages
 * @property {string[]=} countries
 * @property {string} image
 * @property {string} poster_url
 * @property {string[]} directors
 * @property {string[]} writers
 * @property {string[]} actors
 * @property {string[]} genres
 * @property {string} date_published
 * @property {string} duration
 * @property {string} summary
 * @property {DoubanRatingDto} rating
 * @property {"wish" | "collect"=} user_interest
 * @property {number=} user_rating
 */

/**
 * @typedef {object} DoubanInterestRequestDto
 * @property {"wish" | "collect"} interest
 * @property {number | null=} rating
 * @property {string=} tags
 */

/**
 * @typedef {object} DoubanInterestResponseDto
 * @property {boolean} ok
 * @property {"wish" | "collect"} interest
 * @property {number | null} rating
 * @property {string} tags
 */

/** @typedef {"complete" | "partial"} DoubanSnapshotCompleteness */

/**
 * @typedef {object} DoubanLibraryItemDto
 * @property {string} source
 * @property {string} media_type
 * @property {string} id
 * @property {string} subject_id
 * @property {string} title
 * @property {string} url
 * @property {string} abstract_text
 * @property {string} abstract_2
 * @property {string} cover_url
 * @property {string} poster_url
 * @property {"wish" | "collect"} status
 * @property {string} status_label
 * @property {string} date
 * @property {string} comment
 * @property {string[]} tags
 * @property {number | null} user_rating
 */

/**
 * @typedef {object} DoubanLibraryListDto
 * @property {"wish" | "collect"} status
 * @property {string} label
 * @property {DoubanLibraryItemDto[]} items
 * @property {DoubanSnapshotCompleteness} completeness
 * @property {number} fetched_pages
 * @property {boolean} truncated_by_limit
 * @property {boolean} end_observed
 */

/**
 * @typedef {object} DoubanLibraryResponseDto
 * @property {string} source
 * @property {boolean} cached
 * @property {number} fetched_at
 * @property {number} ttl_seconds
 * @property {number} limit
 * @property {DoubanLibraryListDto} wish
 * @property {DoubanLibraryListDto} collect
 */

/**
 * @typedef {object} DoubanTagCountDto
 * @property {string} tag
 * @property {number} count
 * @property {string} category
 */

/**
 * @typedef {object} DoubanTagCategoryDto
 * @property {string} name
 * @property {string} wanted_tag
 */

/**
 * @typedef {object} DoubanTagHistoryResponseDto
 * @property {string} source
 * @property {boolean} cached
 * @property {number | null} updated_at
 * @property {string[]} tags
 * @property {DoubanTagCountDto[]} tag_counts
 * @property {DoubanTagCategoryDto[]} subscription_categories
 */

/**
 * @typedef {object} DoubanQrStartResponseDto
 * @property {string} session_id
 * @property {string} image_url
 */

/**
 * @typedef {object} DoubanQrPollResponseDto
 * @property {boolean} done
 * @property {string} login_status
 * @property {string} message
 * @property {string} description
 * @property {boolean} cookie_saved
 */

/**
 * @typedef {object} ApiErrorDto
 * @property {string} code
 * @property {string} message
 */

/**
 * @typedef {object} NormalizedSubscriptionSummaryPage
 * @property {string | null} next_cursor
 * @property {string[]} ordered_ids
 * @property {Record<string, SubscriptionSummaryDto>} records
 */
/** @typedef {NormalizedSubscriptionSummaryPage & {next_cursor: null}} NormalizedSubscriptionSummaryState */

/** @type {readonly SubscriptionMediaKind[]} */
export const SUBSCRIPTION_MEDIA_KINDS = Object.freeze(["movie", "tv"]);
/** @type {readonly SubscriptionLifecycleState[]} */
export const SUBSCRIPTION_LIFECYCLE_STATES = Object.freeze([
  "queued",
  "meta",
  "searching",
  "downloading",
  "linking",
  "completed",
]);
/** @type {readonly SubscriptionExecutionState[]} */
export const SUBSCRIPTION_EXECUTION_STATES = Object.freeze(["idle", "running"]);
/** @type {readonly SubscriptionAttentionTag[]} */
export const SUBSCRIPTION_ATTENTION_TAGS = Object.freeze([
  "waiting_release",
  "failed",
  "retry_blocked",
  "skipped",
  "needs_reconciliation",
]);
export const SUBSCRIPTION_SUMMARY_FIELDS = Object.freeze([
  "subject_id",
  "revision",
  "active",
  "inactive_at",
  "last_seen_snapshot_id",
  "media_kind",
  "schedulable",
  "blocked_reason",
  "lifecycle_state",
  "execution_state",
  "next_attempt_at",
  "retry_count",
  "max_retries",
  "retry_blocked",
  "force_eligible_once",
  "updated_at",
  "title",
  "release_year",
  "poster_url",
  "category_text",
  "douban_sort_time",
  "attention_tags",
]);
